[workspace]
resolver = "2"
members = [
    "glue",
    "nanoservices/experiments/coremod",
    "nanoservices/experiments/dal",
    "nanoservices/experiments/actix",
    "nanoservices/auth/core",
    "nanoservices/auth/actix",
    "nanoservices/auth/dal",
    "ingress",
]

[workspace.package]
edition      = "2024"
rust-version = "1.88"
version      = "0.1.0"

[workspace.dependencies]
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio-native-tls", "migrate"] }
