[package]
name = "auth_actix_server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
actix-web = "4.5.1"
auth-core = { path = "../core" }
auth-dal = { path = "../dal/" }
glue = { path = "../../../glue/", features = ["actix"] }
base64 = "0.22.1"
serde = { version = "1.0.197", features = ["derive"] }
dotenv = "0.15.0"
